const P=s=>s.split('|').map(x=>{const[a,b='',note='']=x.split('=');return{verb:a,answer:b||null,noForm:!b,note}});
const data={
'ap':P('читать=читающий|гнать=гонящий|брить=бреющий|строить=строящий|держать=держащий|писать=пишущий|дышать=дышащий|лечить=лечащий|слышать=слышащий|рисовать=рисующий|смотреть=смотрящий|клеить=клеящий|видеть=видящий|сеять=сеющий|ненавидеть=ненавидящий|любить=любящий|обидеть=|таять=тающий|вертеть=вертящий|хранить=хранящий|зависеть=зависящий|бороться=борющийся|терпеть=терпящий|колоть=колющий|стелить=стелющий|говорить=говорящий|полоть=полющий|лететь=летящий|молоть=мелющий|сидеть=сидящий'),
'apa':P('читать=читавший|нести=нёсший|сделать=сделавший|принести=принёсший|решить=решивший|унести=унёсший|построить=построивший|расти=росший|написать=написавший|вырасти=выросший|открыть=открывший|ползти=ползший|услышать=услышавший|выползти=выползший|потерять=потерявший|печь=пёкший|нарисовать=нарисовавший|испечь=испёкший|проверить=проверивший|беречь=берёгший|заметить=заметивший|сберечь=сберёгший|прочитать=прочитавший|стеречь=стерёгший|рассказать=рассказавший|мочь=могший|улыбнуться=улыбнувшийся|замёрзнуть=замёрзший|увидеть=увидевший|погибнуть=погибший'),
'pr':P('читать=читаемый|брить=|гнать=гонимый|проверять=проверяемый|держать=|уважать=уважаемый|дышать=|хранить=хранимый|слышать=слышимый|решать=решаемый|смотреть=|обсуждать=обсуждаемый|видеть=видимый|изучать=изучаемый|ненавидеть=ненавидимый|выполнять=выполняемый|обидеть=|создавать=создаваемый|вертеть=вертимый=Редкая нормативная форма; употребляется нечасто.|любить=любимый|зависеть=|носить=носимый|терпеть=терпимый|вести=ведомый|стелить=стелимый=Редкая нормативная форма; употребляется нечасто.|строить=строимый|управлять=управляемый|бежать=|улыбаться=|спать='),
'pp':P('прочитать=прочитанный|брить=бритый|гнать=|посеять=посеянный|держать=держанный=Редкая нормативная форма; употребляется нечасто.|построить=построенный|дышать=|решить=решённый|слышать=слышанный|принести=принесённый|смотреть=|закрыть=закрытый|видеть=виденный|сжать=сжатый|ненавидеть=|написать=написанный|обидеть=обиженный|открыть=открытый|вертеть=верченный=Редкая нормативная форма; употребляется нечасто.|увидеть=увиденный|зависеть=|испечь=испечённый|терпеть=|разбить=разбитый|стелить=стеленный=Редкая нормативная форма; употребляется нечасто.|подмести=подметённый|потерять=потерянный|улыбаться=|бежать=|спать=')};
const ids={'active-present':'ap','active-past':'apa','passive-present':'pr','passive-past':'pp'};
const titles={'active-present':'Действительные причастия настоящего времени','active-past':'Действительные причастия прошедшего времени','passive-present':'Страдательные причастия настоящего времени','passive-past':'Страдательные причастия прошедшего времени'};
const captions={'active-present':'действительное причастие настоящего времени','active-past':'действительное причастие прошедшего времени','passive-present':'страдательное причастие настоящего времени','passive-past':'страдательное причастие прошедшего времени'};
const order=['active-present','active-past','passive-present','passive-past'];
const hints={
'active-present':{title:'Подсказка: действительное причастие настоящего времени',steps:[['Проверьте вид глагола','Причастие настоящего времени образуется только от глагола несовершенного вида.'],['Поставьте глагол в форму 3-го лица множественного числа','Пример: читать → читают.'],['Выделите основу настоящего времени','Основа настоящего времени: читают → чита-.'],['Определите спряжение глагола','I спр.: -ут, -ют. II спр.: -ат, -ят. Пример: читают → I спряжение.'],['Присоедините суффикс причастия','I спр. → -ущ-/-ющ-. II спр. → -ащ-/-ящ-. Пример: чита- + -ющ- = читающий.']],example:['читать (НСВ)','читают<br>(3-е л., мн. ч.)','чита-<br>(основа наст. вр.)','I спряжение<br>(-ут/-ют)','читающий<br>(действит. прич. наст. вр.)'],foot:'<b>Исключения по спряжению:</b> I спряжение: <i>брить, стелить</i>. II спряжение: <i>гнать, держать, дышать, слышать, смотреть, видеть, ненавидеть, обидеть, зависеть, терпеть, вертеть</i>.'},
'active-past':{title:'Подсказка: действительное причастие прошедшего времени',steps:[['Образуйте форму прошедшего времени','Пример: прочитать → прочитал; нести → нёс.'],['Выделите основу прошедшего времени','Примеры: прочитал → прочита-; нёс → нёс-.'],['Посмотрите, чем заканчивается основа','Основа на гласный → -вш-. Основа на согласный → -ш-.'],['Выберите суффикс причастия','Примеры: прочита- + -вш-; нёс- + -ш-.'],['Запишите готовую форму','Примеры: прочитавший; нёсший.']],example:['прочитать','прочитал<br>(прош. вр.)','прочита-<br>(основа прош. вр.)','-вш-','прочитавший<br>(действит. прич. прош. вр.)'],foot:'<b>Напоминание:</b> если инфинитив и прошедшее время дают разные основы, ориентируйтесь на форму прошедшего времени: <i>нести → нёс → нёсший</i>.'},
'passive-present':{title:'Подсказка: страдательное причастие настоящего времени',steps:[['Проверьте вид глагола','Страдательное причастие настоящего времени образуется только от глагола несовершенного вида.'],['Проверьте переходность','Форма образуется только от переходного глагола.'],['Выделите основу настоящего времени','Примеры: проверяем → проверя-; храним → хран-.'],['Определите спряжение глагола','I спр.: проверяем. II спр.: храним.'],['Присоедините суффикс причастия','I спр. → -ем-. II спр. → -им-. Примеры: проверя- + -ем- = проверяемый; хран- + -им- = хранимый.']],example:['проверять<br>(НСВ, перех.)','проверяем<br>(наст. вр.)','проверя-<br>(основа наст. вр.)','I спряжение','проверяемый<br>(страдат. прич. наст. вр.)'],foot:'<b>Важно:</b> даже у подходящего глагола страдательное причастие настоящего времени образуется не всегда. Если формы нет, нажмите <i>«Не образуется»</i>.'},
'passive-past':{title:'Подсказка: страдательное причастие прошедшего времени',steps:[['Проверьте переходность глагола','Страдательное причастие прошедшего времени обычно образуется от переходного глагола.'],['Определите основу слова','Примеры основ: прочита-, посея-, реши-, закры-.'],['Проверьте -нн-','Часто: -ать → -анный, -ять → -янный. Примеры: прочитать → прочитанный; посеять → посеянный.'],['Проверьте -енн-/-ённ-','Примеры: решить → решённый; построить → построенный.'],['Проверьте -т-','Примеры: закрыть → закрытый; сжать → сжатый. Если формы нет, нажмите «Не образуется».']],example:['решить<br>(переходный)','реши-<br>(основа)','-ённ-','решённый','страдат. прич.<br>прош. вр.'],foot:'<b>Важно:</b> страдательное причастие прошедшего времени образуется не от каждого переходного глагола. В спорных случаях в тренажёре используется ответ <i>«Не образуется»</i>.'}}
const states=Object.fromEntries(order.map(k=>[k,newState(k)]));let current=order[0];
function newState(k){return{idx:0,attempts:Array(data[ids[k]].length).fill(0),checks:0,first:0,next:false,no:false,done:false,hint:false,draft:'',fb:'',fbClass:'empty'}}
function norm(s){return(s||'').trim().toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ')}
function esc(s){return(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function scale(){const a=document.getElementById('app'),w=document.getElementById('wrap'),k=Math.min(innerWidth/1280,innerHeight/720);a.style.transform=`scale(${k})`;w.style.width=1280*k+'px';w.style.height=720*k+'px'}addEventListener('resize',scale);scale();
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{current=b.dataset.id;render()});
function hintHTML(k){const h=hints[k],s=states[k];return`<div class="hint ${s.hint?'open':''}"><div class="hint-title"><span>${h.title}</span><span>${s.hint?'▴':'▾'}</span></div><div class="hint-grid">${h.steps.map((x,i)=>`<div class="hint-step"><div class="step-no">${i+1}</div><div class="step-title">${x[0]}</div><div class="step-text">${x[1]}</div></div>`).join('')}</div><div class="example"><b>Пример</b><div class="example-row">${h.example.map(x=>`<div class="example-item">${x}</div>`).join('')}</div></div><div class="exceptions">${h.foot}</div></div>`}
function render(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.id===current));document.getElementById('title').textContent=titles[current];const bi=order.indexOf(current)+1;document.getElementById('blockProgress').textContent=`Блок ${bi} из 4`;document.getElementById('fill').style.width=bi*25+'%';document.getElementById('allStatus').textContent=order.every(k=>states[k].done)?'Все 4 блока завершены.':'';renderBlock(current)}
function renderBlock(k){const s=states[k],arr=data[ids[k]],host=document.getElementById('drill');if(s.done){const r=arr.map((x,i)=>[x.verb,s.attempts[i]]).filter(x=>x[1]>1);host.innerHTML=`<div class="summary"><h2>${titles[k]} · блок завершён</h2><div class="sumgrid"><div class="sum"><b>30</b><span>слов выполнено</span></div><div class="sum"><b>${s.first}</b><span>с первой попытки</span></div><div class="sum"><b>${s.checks}</b><span>всего проверок</span></div></div><div class="difficult">${r.length?'<b>Больше одной попытки:</b> '+r.map(x=>x[0]+' — '+x[1]).join(' · '):'Все слова выполнены с первой попытки.'}</div><button class="restart" id="restart">Пройти блок ещё раз</button></div>`;document.getElementById('restart').onclick=()=>{const h=s.hint;states[k]=newState(k);states[k].hint=h;render()};return}const x=arr[s.idx];host.innerHTML=`<div class="head"><div class="counter">Глагол ${s.idx+1} из 30</div><div class="stat">С первой попытки: ${s.first}</div><div class="stat">Проверок: ${s.checks}</div></div><div class="wordbar"><i style="width:${(s.idx+1)/30*100}%"></i></div><div class="card"><div class="caption">Образуйте ${captions[k]} от глагола:</div><div class="verb">${x.verb}</div><div class="answer"><input id="inp" value="${esc(s.draft)}" placeholder="Введите причастие" ${s.next?'disabled':''}><button class="check" id="check">Проверить</button><button class="hint-btn ${s.hint?'active':''}" id="hint">Подсказка</button></div><button class="noform ${s.no?'active':''}" id="no" ${s.next?'disabled':''}>Не образуется</button><div class="feedback ${s.fbClass}" id="fb">${s.fb||'.'}</div><button class="next ${s.next?'':'hidden'}" id="next">${s.idx===29?'Завершить блок':'Следующий глагол →'}</button>${hintHTML(k)}</div>`;const inp=document.getElementById('inp');inp.oninput=()=>{s.draft=inp.value;if(s.no)s.no=false};inp.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check(k)}};document.getElementById('check').onclick=()=>check(k);document.getElementById('hint').onclick=()=>{s.hint=!s.hint;renderBlock(k)};document.getElementById('no').onclick=()=>{if(!s.next){s.no=!s.no;renderBlock(k)}};document.getElementById('next').onclick=()=>next(k);if(!s.next)setTimeout(()=>inp.focus(),0)}
function check(k){const s=states[k],x=data[ids[k]][s.idx];if(s.next)return;const v=norm(s.draft),no=s.no||v==='не образуется';if(!v&&!no){s.fb='Введите причастие или нажмите «Не образуется».';s.fbClass='bad';return renderBlock(k)}s.attempts[s.idx]++;s.checks++;const ok=x.noForm?no:(!no&&norm(x.answer)===v);if(ok){if(s.attempts[s.idx]===1)s.first++;s.next=true;s.fb=x.noForm?'Верно: такая форма не образуется.':`Верно: ${x.answer}.`;s.fbClass=x.note?'rare':'good';if(x.note)s.fb+=' '+x.note}else{s.fb=x.noForm?'Пока неверно. Проверьте условия образования: возможно, форма не образуется.':'Пока неверно. Вернитесь к основе и суффиксу нужного типа причастия.';s.fbClass='bad'}renderBlock(k)}
function next(k){const s=states[k];if(!s.next)return;s.next=false;s.no=false;s.draft='';s.fb='';s.fbClass='empty';if(s.idx===29)s.done=true;else s.idx++;render()}
render();
