const sortItems=[['грозовые тучи','adj'],['сверкающие молнии','part'],['раскатистый гром','adj'],['уходящая гроза','part'],['посветлевшее небо','part'],['разноцветная радуга','adj'],['формирующееся государство','part'],['кочующие племена','part'],['защитные сооружения','adj'],['осаждённая крепость','part'],['взлетающая ракета','part'],['легендарные полёты','adj']];
const bank=document.getElementById('cardBank');const zones=[...document.querySelectorAll('.drop-zone')];let dragged=null;function makeCard([text,type]){const d=document.createElement('div');d.className='phrase-card';d.draggable=true;d.textContent=text;d.dataset.type=type;d.addEventListener('dragstart',()=>dragged=d);return d}function resetSort(){bank.innerHTML='';zones.forEach(z=>[...z.querySelectorAll('.phrase-card')].forEach(c=>c.remove()));[...sortItems].sort(()=>Math.random()-.5).forEach(x=>bank.appendChild(makeCard(x)));setStatus('sortStatus','',true)}[bank,...zones].forEach(c=>{c.addEventListener('dragover',e=>e.preventDefault());c.addEventListener('drop',e=>{e.preventDefault();if(dragged)c.appendChild(dragged)})});document.getElementById('checkSort').onclick=()=>{document.querySelectorAll('.phrase-card').forEach(c=>c.classList.remove('good','bad'));if(bank.querySelector('.phrase-card'))return setStatus('sortStatus','Сначала распредели все карточки.',false);let ok=0,total=0;zones.forEach(z=>z.querySelectorAll('.phrase-card').forEach(c=>{total++;const good=c.dataset.type===z.dataset.zone;c.classList.add(good?'good':'bad');if(good)ok++}));setStatus('sortStatus',ok===total?'Всё верно!':`Верно: ${ok} из ${total}.`,ok===total)};document.getElementById('resetSort').onclick=resetSort;resetSort();

document.querySelectorAll('.meaning-pair').forEach(b=>b.onclick=()=>{document.querySelectorAll('.meaning-pair').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('meaningNote').textContent=b.dataset.note});

function wireResearch(containerId,summaryId){const box=document.getElementById(containerId);const summary=document.getElementById(summaryId);const cards=[...box.querySelectorAll('.research-card')];cards.forEach(card=>{card.querySelectorAll('.choice').forEach(btn=>btn.onclick=()=>{card.querySelectorAll('.choice').forEach(x=>x.classList.remove('good','bad'));const ok=btn.dataset.correct==='1';btn.classList.add(ok?'good':'bad');card.dataset.done=ok?'1':'0';if(cards.every(c=>c.dataset.done==='1'))summary.classList.remove('hidden')})})}wireResearch('verbResearch','verbSummary');wireResearch('adjResearch','adjSummary');

const features=[['вид','verb'],['время','verb'],['залог','verb'],['возвратность','verb'],['склонение','adj'],['изменение по родам в ед. числе','adj'],['согласование с существительным','adj'],['полная форма — определение','adj'],['краткая форма — сказуемое','adj']];const featureBank=document.getElementById('featureBank');const featureZones=[...document.querySelectorAll('[data-feature-zone]')];let featureDragged=null;function makeFeature([text,type]){const d=document.createElement('div');d.className='feature-card';d.draggable=true;d.textContent=text;d.dataset.type=type;d.addEventListener('dragstart',()=>featureDragged=d);return d}function resetFeatures(){featureBank.innerHTML='';featureZones.forEach(z=>[...z.querySelectorAll('.feature-card')].forEach(c=>c.remove()));[...features].sort(()=>Math.random()-.5).forEach(x=>featureBank.appendChild(makeFeature(x)));setStatus('featureStatus','',true)}[featureBank,...featureZones].forEach(c=>{c.addEventListener('dragover',e=>e.preventDefault());c.addEventListener('drop',e=>{e.preventDefault();if(featureDragged)c.appendChild(featureDragged)})});document.getElementById('checkFeatures').onclick=()=>{document.querySelectorAll('.feature-card').forEach(c=>c.classList.remove('good','bad'));if(featureBank.querySelector('.feature-card'))return setStatus('featureStatus','Сначала распредели все признаки.',false);let ok=0,total=0;featureZones.forEach(z=>z.querySelectorAll('.feature-card').forEach(c=>{total++;const good=c.dataset.type===z.dataset.featureZone;c.classList.add(good?'good':'bad');if(good)ok++}));setStatus('featureStatus',ok===total?'Схема заполнена верно!':`Верно: ${ok} из ${total}.`,ok===total)};document.getElementById('resetFeatures').onclick=resetFeatures;resetFeatures();

const groups={adj:{sources:['гроза','космос','граница','земля'],pairs:{гроза:'грозовой',космос:'космический',граница:'пограничный',земля:'земной'},s:'adjSources',t:'adjTargets'},part:{sources:['сверкать','уходить','взлетать','кочевать'],pairs:{сверкать:'сверкающий',уходить:'уходящая',взлетать:'взлетающая',кочевать:'кочующие'},s:'partSources',t:'partTargets'}};let selected=null,matched=0;function renderMatches(key){const g=groups[key],s=document.getElementById(g.s),t=document.getElementById(g.t);g.sources.forEach(v=>s.appendChild(matchEl(v,key,'source')));Object.values(g.pairs).sort(()=>Math.random()-.5).forEach(v=>t.appendChild(matchEl(v,key,'target')))}function matchEl(value,group,role){const d=document.createElement('div');d.className='match-item';d.textContent=value;d.dataset.value=value;d.dataset.group=group;d.dataset.role=role;d.onclick=()=>matchClick(d);return d}function matchClick(d){if(d.classList.contains('matched'))return;if(d.dataset.role==='source'){document.querySelectorAll('.match-item.selected').forEach(x=>x.classList.remove('selected'));d.classList.add('selected');selected=d;return}if(!selected||selected.dataset.group!==d.dataset.group)return setStatus('matchStatus','Сначала выбери слово слева.',false);const g=groups[d.dataset.group];if(g.pairs[selected.dataset.value]===d.dataset.value){selected.classList.remove('selected');selected.classList.add('matched');d.classList.add('matched');matched++;selected=null;setStatus('matchStatus',matched===8?'Все пары найдены!':'Верная пара.',true)}else setStatus('matchStatus','Не эта пара. Попробуй ещё раз.',false)}renderMatches('adj');renderMatches('part');

function norm(s){return s.trim().toLowerCase().replaceAll('ё','е')}
const answer1=document.getElementById('answer1');const answer2=document.getElementById('answer2');const mainFormula=document.querySelector('.conclusion-panel .formula');if(mainFormula){mainFormula.style.visibility='hidden';mainFormula.style.opacity='0';mainFormula.style.transition='opacity .35s ease'}
function hideMainFormula(){if(mainFormula){mainFormula.style.visibility='hidden';mainFormula.style.opacity='0'}}
function showMainFormula(){if(mainFormula){mainFormula.style.visibility='visible';requestAnimationFrame(()=>mainFormula.style.opacity='1')}}
answer1.addEventListener('input',hideMainFormula);answer2.addEventListener('input',hideMainFormula);
document.getElementById('checkConclusion').onclick=()=>{const a1=norm(answer1.value),a2=norm(answer2.value);const ok1=['глагола','глагол','от глагола'].includes(a1),ok2=['действие','действие предмета'].includes(a2);if(ok1&&ok2){setStatus('conclusionStatus','Вывод верный!',true);showMainFormula()}else{setStatus('conclusionStatus','Есть неточность.',false);hideMainFormula()}};
document.getElementById('hintConclusion').onclick=()=>{answer1.value='глагола';answer2.value='действие';hideMainFormula();setStatus('conclusionStatus','Подсказка открыта. Нажми «Проверить вывод».',true)};
function setStatus(id,text,ok){const el=document.getElementById(id);if(!el)return;el.textContent=text;el.className='status '+(text?(ok?'good':'bad'):'')}
const screens=[...document.querySelectorAll('.lesson-screen')];let current=0;function showScreen(i){current=Math.max(0,Math.min(i,screens.length-1));screens.forEach((s,n)=>s.classList.toggle('active',n===current));document.getElementById('screenCurrent').textContent=current+1;document.getElementById('screenTotal').textContent=screens.length;document.getElementById('prevScreen').disabled=current===0;document.getElementById('nextScreen').disabled=current===screens.length-1}document.getElementById('prevScreen').onclick=()=>showScreen(current-1);document.getElementById('nextScreen').onclick=()=>showScreen(current+1);showScreen(0);